import {
    EmailListRequest, EmailListResponse,
    EmailDetailRequest, EmailDetailResponse,
    EmailSendRequest, EmailSendResponse,
    EmailReceiveRequest, EmailReceiveResponse,
    EmailScanRequest, EmailScanResponse,
    EmailDeleteRequest, EmailDeleteResponse,
    EmailRestoreRequest, EmailRestoreResponse,
    EmailPurgeRequest, EmailPurgeResponse,
    EmailPushRequest, EmailPushResponse,
    EmailAttachmentRequest, EmailAttachmentResponse,
    SendLogListRequest, SendLogListResponse,
    SendLogUpdateRequest, SendLogUpdateResponse,
} from "./email.interface";

export const emailRoutes = {
    base: "/api",
    prefix: "/email",
    list:       { path: "/list",       request: {} as EmailListRequest,       response: {} as EmailListResponse },
    detail:     { path: "/detail",     request: {} as EmailDetailRequest,     response: {} as EmailDetailResponse },
    send:       { path: "/send",       request: {} as EmailSendRequest,       response: {} as EmailSendResponse },
    receive:    { path: "/receive",    request: {} as EmailReceiveRequest,    response: {} as EmailReceiveResponse },
    scan:       { path: "/scan",       request: {} as EmailScanRequest,       response: {} as EmailScanResponse },
    delete:     { path: "/delete",     request: {} as EmailDeleteRequest,     response: {} as EmailDeleteResponse },
    restore:    { path: "/restore",    request: {} as EmailRestoreRequest,    response: {} as EmailRestoreResponse },
    purge:      { path: "/purge",      request: {} as EmailPurgeRequest,      response: {} as EmailPurgeResponse },
    push:       { path: "/push",       request: {} as EmailPushRequest,       response: {} as EmailPushResponse },
    sendLogList:   { path: "/send-log/list",   request: {} as SendLogListRequest,   response: {} as SendLogListResponse },
    sendLogUpdate: { path: "/send-log/update", request: {} as SendLogUpdateRequest, response: {} as SendLogUpdateResponse },
    attachment: { path: "/attachment", request: {} as EmailAttachmentRequest, response: {} as EmailAttachmentResponse },
} as const;
