import {
    MailboxListRequest, MailboxListResponse,
    MailboxSaveRequest, MailboxSaveResponse,
    MailboxDeleteRequest, MailboxDeleteResponse,
    MailboxAddressesRequest, MailboxAddressesResponse,
    MailboxSyncRequest, MailboxSyncResponse,
    MailboxTestRequest, MailboxTestResponse,
    MailboxProvidersRequest, MailboxProvidersResponse,
    MailboxGrantGetRequest, MailboxGrantGetResponse,
    MailboxGrantSaveRequest, MailboxGrantSaveResponse,
    MailboxGrantRevokeRequest, MailboxGrantRevokeResponse,
    MailboxGrantListRequest, MailboxGrantListResponse,
    MailboxTauthInfoRequest, MailboxTauthInfoResponse,
    MailboxLabelSaveRequest, MailboxLabelSaveResponse,
    MailboxLabelRemoveRequest, MailboxLabelRemoveResponse,
    MailboxRecipientsRequest, MailboxRecipientsResponse,
    MailboxSortPushBackRequest, MailboxSortPushBackResponse,
} from "./mailbox.interface";

export const mailboxRoutes = {
    base: "/api",
    prefix: "/mailbox",
    list:          { path: "/list",           request: {} as MailboxListRequest,          response: {} as MailboxListResponse },
    save:          { path: "/save",           request: {} as MailboxSaveRequest,          response: {} as MailboxSaveResponse },
    delete:        { path: "/delete",         request: {} as MailboxDeleteRequest,        response: {} as MailboxDeleteResponse },
    addresses:     { path: "/addresses",      request: {} as MailboxAddressesRequest,     response: {} as MailboxAddressesResponse },
    sync:          { path: "/sync",           request: {} as MailboxSyncRequest,          response: {} as MailboxSyncResponse },
    test:          { path: "/test",           request: {} as MailboxTestRequest,          response: {} as MailboxTestResponse },
    providers:     { path: "/providers",      request: {} as MailboxProvidersRequest,     response: {} as MailboxProvidersResponse },
    recipients:    { path: "/recipients",     request: {} as MailboxRecipientsRequest,    response: {} as MailboxRecipientsResponse },
    labelSave:     { path: "/label-save",     request: {} as MailboxLabelSaveRequest,     response: {} as MailboxLabelSaveResponse },
    labelRemove:   { path: "/label-remove",   request: {} as MailboxLabelRemoveRequest,   response: {} as MailboxLabelRemoveResponse },
    grantGet:      { path: "/grant-get",      request: {} as MailboxGrantGetRequest,       response: {} as MailboxGrantGetResponse },
    grantCreate:   { path: "/grant-create",   request: {} as MailboxGrantSaveRequest,      response: {} as MailboxGrantSaveResponse },
    grantRevoke:   { path: "/grant-revoke",   request: {} as MailboxGrantRevokeRequest,    response: {} as MailboxGrantRevokeResponse },
    grantList:     { path: "/grant-list",     request: {} as MailboxGrantListRequest,      response: {} as MailboxGrantListResponse },
    tauthInfo:     { path: "/tauth-info",     request: {} as MailboxTauthInfoRequest,      response: {} as MailboxTauthInfoResponse },
    sortPushBack:  { path: "/sort-push-back", request: {} as MailboxSortPushBackRequest,   response: {} as MailboxSortPushBackResponse },
} as const;
